image: denoland/deno:1.42.3

default:
  interruptible: true

stages:
  - test

fmt:
  stage: test
  script: deno fmt --check

lint:
  stage: test
  script: deno lint

check:
  stage: test
  script: deno check

test:
  stage: test
  script: deno test
